### ISSUE TITLE
dropdown menu doesn't work anymore

### ISSUE THREAD

**Issue by flth** [Rundiz-WP/bootstrap-basic4#31]
Seems with WP 5.0.3 there is a bug that dropdown (sub menus) doesn't work anymore. Clicking on an entry doesn't do anything. Reason unknown for me

**Comment by ve3** [comment]
This is because of the [bug in Bootstrap 4.2.1](https://github.com/twbs/bootstrap/issues/27903) not from other.

From that issue, please see examples from these links.
1. https://codepen.io/anon/pen/oJZKXW Drop down works.
2. https://codepen.io/anon/pen/BvWXNO Drop down doesn't work.

To hot fix in your website, please add custom menu as dropdown parent menu and use `#` as link and keep sub menu no change.

This bug will be fixed once Bootstrap 4.3 released as seen in issue's project described that shipped in [v4.3.](https://github.com/twbs/bootstrap/projects/16#card-16081255)

If Bootstrap 4.3 released, I will update this theme and release as soon as possible.
So, I will keep "this" issue open and make a comment again once the theme released.

**Comment by flth** [comment]
Hello, thanks for the very reply.. I've read the bug at BS, I've checked the examples, I've done that hotfix. The code looks like it should (href="#"), but it still doesn't work. Very puzzled

**Comment by ve3** [comment]
Please take a look at my screenshot.
[![Screenshot-2019-01-15-Menus-rundiz-Word-Press.png](https://i.postimg.cc/63pm2kbr/Screenshot-2019-01-15-Menus-rundiz-Word-Press.png)](https://postimg.cc/FfwZwB4z)
And here is my website front-end result. https://rundiz.com/

Make sure that you use **Custom Link** with `#` as URL for parent menu that contain dropdown.

If your site use any cache, please clear all the cache first and then CTRL+F5 to force reload front page (without cache).
I hope that this will be helped, please tell me again if it is working or not.

**Comment by flth** [comment]
hi, yes exactly what I did, I've checked the frontend and it is correct in the syntax, still doesn't work. Disabled Cache and tried also Chrome...
https://abload.de/img/screenfgj53.png
really no idea what is wrong, before WP 5.0.3 it was working

**Comment by ve3** [comment]
That is really strange because all my local and online WordPress using this theme can fix with this.

If all the parent menu that contain dropdown is already custom menu and still not working, I recommend you to roll back to use **[Bootstrap Basic 1.2](https://github.com/Rundiz-WP/bootstrap-basic4/releases/tag/v1.2)** instead and skip or disable update for this theme until I release the new version.

Sorry for the inconvenient.

**Comment by coliff** [comment]
The responsive hamburger menu is working fine for me - maybe your issue is unrelated to this? Do you have a public link to your site in question so we can take a look?

**Comment by ve3** [comment]
Thank you @coliff .
But that seems to be the same result as I provided. (Use `#` as URL with **Custom Link** menu).
This is my a little improved for dynamically change all dropdown links.

```
// hot fix Bootstrap 4.2.1
$('.dropdown-toggle').each(function(index, item) {
    $(this).attr('data-originalhref', $(this).attr('href'));// keep original to data-originalhref
    $(this).attr('href', '#');// replace href attribute.
});
```

**Comment by flth** [comment]
NSFW https://fetishlady-marissa.com

**Comment by ve3** [comment]
@flth From your URL, it seems that bootstrap.bundle.min.js is missing. That's why it is not working.
Some plugins may unload this file.

https://github.com/Rundiz-WP/bootstrap-basic4/blob/master/inc/classes/BootstrapBasic4.php#L89
These are assets (CSS, JS) that will be loaded on front-end.

**Comment by flth** [comment]
Ok, I had removed that script before shortly for testing. Have it back and can't explain but it works again after I created a new menu entry with the same settings (url as #).
Thank you two for the heads up and solved so far.

**Comment by ve3** [comment]
https://themes.trac.wordpress.org/ticket/65514
