### ISSUE TITLE
Questions about Bootstrap Basic4 and more

### ISSUE THREAD

**Issue by Mariann90** [Rundiz-WP/bootstrap-basic4#41]
Dear vee,

I like your Bootstrap Basic4 theme found on Wordpress.org.
This is the reason, why I would like to ask you some questions about how to start a website-builder service. I am sure, you can give me some excellent advices. Unfortunately, I could  not find any email address of yours, so I decided to write here.

Circumstances:
Me and my employer are planning to start a service in Hungary. We - or preferably me - will build simple websites based on Wordpress
for small and medium-sized companies. We want to provide secure and responsive sites, which can get good ranking in Google search results.

What we have now:
- rented storage space from a server hosting company (circa 450 MB free space)
- .hu domains
- php 7.3 
- MySQL 5.6
- Wordpress 5.6 (english version)
- FTP-connection
- no cPanel (unfortunately)

Our plan is trying out and using some core features of WP, and installing some plugins and a theme, to gain some experiences, and - of course - to practice.
We have an eye on being compliant with Google, so we would like to choose Bootstrap-based themes - like yours - to ensure that. I mean to make our sites responsive.
We prefer to use the freshest versions, like BT v.4 or 5-based ones.
We think, we will need your theme, a backup automatism, a security-solution and a contact form + captcha on the very beginning to build simple and well-functioning sites.

The content will be written in Hungarian.

I will check these sites with:
Google Mobile-Friendly Test (https://search.google.com/test/mobile-friendly)
Google PageSpeed Insights (https://developers.google.com/speed/pagespeed/insights/)
a smartphone (or more)
different browsers on desktop, like Firefox or Chrome.
I think also on W3C validator, but with CMS the result can never be a clean and valid code, as far as I know. (https://validator.w3.org/).

My questions to you:
What do you think? Is this plan good and reasonable? Or is there any trap that we couldn't realize yet? 
Is something missing?

To be honest, I am not an expert programmer, I have just the very basics in my head. This is why I ask a much more experienced person, like you.

Do you provide consultation service? 

Could you please send me some live example sites, which use Bootstrap Basic4 theme?
Do you plan to upgrade your Bootstrap Basic4 theme to be Bootstrap5 - based? If yes, then when is it expected?
Does this theme has a pro version? What kind of features can it provide?

What are you working nowadays?

I am waiting for your answer, thank you in advance.

**Comment by ve3** [comment]
Hello @Mariann90 
I'm not expert in business. So, I can't give much advice. If your website will serve contents, WordPress is one of many good choices. 
If you want to provide any services that maybe charging for monthly, annually, subscriptions. I would recommend you to create your own application or split that part into your own application. Use framework by your choice. Because create complex service plugin using WordPress maybe spend a lot more time.

> Do you provide consultation service?

Sorry. No, I don't.

> Could you please send me some live example sites, which use Bootstrap Basic4 theme?

Well, at least my own website using it as a parent theme. -> https://rundiz.com

> Do you plan to upgrade your Bootstrap Basic4 theme to be Bootstrap5 - based? If yes, then when is it expected?

No, I don't have a plan to do that. Please read more at https://github.com/Rundiz-WP/bootstrap-basic4/issues/40

> Does this theme has a pro version?

No there has not. Many organizations use "pro" or "premium" version, which is good business model and it can make money. But I don't create this theme for that.
Beside the concept that this theme is made for developers to create their theme easily with basic, no rich features, no additional functions. This theme is create for use with any purpose in completely free of charge.

It is good or bad you can say. I hope that you like it.

> What are you working nowadays?

I run a small business.

I was started to learn coding (myself)  from zero knowledge about programming. In that time, it is very hard to ask for some help from anyone + and because of that.. Today I know a lot of things from many kindness programmers. So, I thanks to them by giving free things to the others.
This is only little story I can share with you.

**Comment by Mariann90** [comment]
Thank you very much for your answer! :)
