### ISSUE TITLE
Title tagline menus centered

### ISSUE THREAD

**Issue by berlinczyk** [Rundiz-WP/bootstrap-basic4#45]
As the topic is not answered on wp forum I ask here again:

I like this clean theme but would prefere Title tagline and menus centered,
Could you please help me with css?

**Comment by ve3** [comment]
I did not get any notification on wordpress.org website that's why I recommended to ask here. Sorry for inconvenient.

This theme is based on Bootstrap 4 so you can use their [Text utilities](https://getbootstrap.com/docs/4.0/utilities/text/).  
To center, use `text-center` in `class` attribute.

Modify your child theme where you want title to be centered by add `text-center` to the class. Example:

```
<h1 class="entry-title text-center"><a href="<?php the_permalink(); ?>" rel="bookmark"><?php the_title(); ?></a></h1>
```

**Comment by berlinczyk** [comment]
No CSS possible? I would be much easier :)

**Comment by berlinczyk** [comment]
Also underline and menu possible?

**Comment by ve3** [comment]
There are a lot of these basic tutorial out there.

https://www.w3schools.com/cssref/pr_text_text-align.php
https://www.w3schools.com/cssref/pr_text_text-decoration.php

**Comment by berlinczyk** [comment]
It doesn't help, I knew this sites:

I tried many options nothing works.
For the author of this theme it should be a question of 5 minutes I guess.

.site-description
{
margin-left: auto;
margin-right: auto;
display: block;
}


.site-title-heading
{
    text-align: center;
}


.site-title
{
    text-align: center;
}


.bootstrap-basic4-topnavbar 
{
    text-align: center;
}


.page-header-sitebrand-topbar 
{
    text-align: center;


and many other variations :(

**Comment by ve3** [comment]
Those CSS should work but if it doesn't then you have to use browser's inspector to see that the CSS was loaded or not, or is it modified by some other rules.

This theme , by default did not have any class to align post title or site title so that `text-align` is working for me and should work for you either.

The [child themes](https://developer.wordpress.org/themes/advanced-topics/child-themes/) document is very good start to design your child theme and override parent theme's CSS.

**Comment by ve3** [comment]
I don't see that how you put those CSS but when it is in the correct class name then all of them should work except you put them as inline style per HTML element, that will not work on whole page.

**Comment by berlinczyk** [comment]
https://urtext.org/

**Comment by berlinczyk** [comment]
Please write me just css code.
You know all names of containers or what whatever.
if possible .)

**Comment by ve3** [comment]
Your `entry-title` class don't have any `text-align` CSS.

**Comment by berlinczyk** [comment]
O! entry-title is what I also wanted, post and page titles centered :) But site title, underline and manus are still not centered

**Comment by ve3** [comment]
Your site title is already centered but it is in the **left** column. If you want it to be center of whole page then you need to create child theme and remove the right column, expand `col-md-6` to be just `col` or `col-md-12`.

Here are documents about how to use browser inspector.
[Firefox](https://developer.mozilla.org/en-US/docs/Learn/Common_questions/What_are_browser_developer_tools).
[Google Chrome](https://www.browserstack.com/guide/inspect-element-in-chrome).
[All other](https://www.computerhope.com/issues/ch002153.htm).

You have to inspect the HTML element you want to change and then try to change it in the right panel to see preview and if it's working then copy the class name to WordPress customizer and apply your changes.

**Comment by berlinczyk** [comment]
Ok, thanks so far, I see that is not possible only with css :(
I will see if I manage it with child theme witch is absolutely unknown to me.


Thx
